name: calma_wear
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  animations: ^2.0.7
  google_generative_ai: ^0.2.2 
  flutter_markdown: ^0.7.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
  
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf